# Generated by Django 3.1.3 on 2020-11-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
