# Generated by Django 3.1.3 on 2020-11-23 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('system', '0002_auto_20201122_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incharge',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('is_incharge', models.BooleanField()),
            ],
        ),
    ]
