# Generated by Django 3.1.3 on 2020-11-24 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_incharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtainedMarks', models.IntegerField()),
                ('totalMarks', models.IntegerField()),
                ('student', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='system.students')),
                ('subject', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='system.subject')),
            ],
        ),
    ]
