# Generated by Django 3.1.3 on 2020-11-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
