# Generated by Django 3.1.3 on 2020-12-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_test_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendense',
            name='month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attendense',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
